version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    profiles:
      - dependencies
    networks:
      - recipe-app-auth-network
  application:
    image: '${APP_IMAGE_NAME}'
    build: .
    env_file: .env
    restart: on-failure
    ports:
      - '3001:3001'
    depends_on:
      - db
    profiles:
      - app
    networks:
      - recipe-app-auth-network
volumes:
  postgres:
    driver: local

networks:
  recipe-app-auth-network:
    driver: bridge
